#!/bin/bash

NAME="links"                                        # Name of the application
DJANGODIR=/var/webapps/links/app                        # Django project directory
LOGFILE=/var/webapps/links/gunicorn.log                 # Log file
NUM_WORKERS=3                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=links.settings               # which settings file should Django use
DJANGO_WSGI_MODULE=links.wsgi                       # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Do deployment actions
if [ $1 == 'deploy' ]
then 
    pip install -r ./requirements.txt
    python ./manage.py migrate
fi

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --daemon \
  --name $NAME \
  --workers $NUM_WORKERS \
  --log-level=debug \
  --log-file="$LOGFILE"